name: nowcastpnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - -e . # This command tells pip to install the project in the current directory
           # in "editable" mode by reading pyproject.toml