defaults:
  - data: dengue_sp
  - model: nowcastpnn
  - _self_

project_info:
  experiment_name: "nowcastpnn_train"
  run_name: "${model.name}_${data.name}" # Name is composed from other configs!

training:
  epochs: 200
  learning_rate: 0.001
  batch_size: 64
  patience: 30

seed: 1234
